### ISSUE TITLE
Github action automatic gradle build gives an error

### ISSUE THREAD

**Issue by wverveer** [wverveer/SLA-report#11]
**Describe the bug**
After adding the [GitHub actions](https://github.com/wverveer/SLA-report/issues/5) to automatic build a branch an error occurred.

**To Reproduce**

- commit a change to a random branch

**Expected behavior**
Build is successful

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
**Error**
`Run gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041[14](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:14)7db7
14
Restore Gradle state from cache
[16](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:16)
Error: Error: Gradle script '/home/runner/work/SLA-report/SLA-report/gradlew' is not executable.
[17](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:17)
Error: Gradle script '/home/runner/work/SLA-report/SLA-report/gradlew' is not executable.
[18](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:18)
    at constants (/home/runner/work/_actions/gradle/gradle-build-action/937999e9cc2425eddc7fd62d1053baf041147db7/dist/src/execution.ts:69:1)
[19](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:19)
    at Object.locateGradleWrapperScript (/home/runner/work/_actions/gradle/gradle-build-action/937999e9cc2425eddc7fd62d1053baf041147db7/dist/src/execution.ts:47:1)
[20](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:20)
    at Generator.next (<anonymous>)
[21](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:21)
    at rejected (/home/runner/work/_actions/gradle/gradle-build-action/937999e9cc2425eddc7fd62d1053baf041147db7/dist/src/execution.ts:26:32)
[22](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:22)
    at new Promise (<anonymous>)
[23](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:23)
    at P (/home/runner/work/_actions/gradle/gradle-build-action/937999e9cc[24](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:24)[25](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:25)eddc7fd62d1053baf041147db7/dist/src/execution.ts:22:28)
24
    at Object.executeGradleBuild (/home/runner/work/_actions/gradle/gradle-build-action/937999e9cc2425eddc7fd62d1053baf041147db7/dist/src/execution.ts:40:1)
25
    at parseCommandLineArguments (/home/runner/work/_actions/gradle/gradle-build-action/937999e9cc2425eddc7fd62d1053baf041147db7/dist/src/main.ts:50:1)
[26](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:26)
    at Generator.next (<anonymous>)
[27](https://github.com/wverveer/SLA-report/runs/5632832945?check_suite_focus=true#step:4:27)
    at fulfilled (/home/runner/work/_actions/gradle/gradle-build-action/937999e9cc2425eddc7fd62d1053baf041147db7/dist/src/main.ts:24:1)`

**Comment by wverveer** [comment]
This is the mentioned error
`Error: Error: Gradle script '/home/runner/work/SLA-report/SLA-report/gradlew' is not executable.`
